/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hangmanClient;
/*
 * ClientGUI.java
 *
 * Created on Nov 7, 2011, 9:41:15 PM
 */
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.*;
/**
 *
 * @author Ahad
 */
public class ClientGUI extends javax.swing.JFrame {

    Socket socket;
    InputStream in;
    OutputStream out;
    PrintWriter pout;
    BufferedReader bin;

    /** Creates new form ClientGUI */
    public ClientGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tHostName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tPortNo = new javax.swing.JTextField();
        bStart = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bConnect = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tWord = new javax.swing.JTextField();
        tDisplay = new javax.swing.JLabel();
        bSend = new javax.swing.JButton();
        lWord = new javax.swing.JLabel();
        lHint = new javax.swing.JLabel();
        lLife = new javax.swing.JLabel();
        lScore = new javax.swing.JLabel();
        lScore1 = new javax.swing.JLabel();
        lWrong = new javax.swing.JLabel();
        lTry = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Host");

        tHostName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHostNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Port");

        tPortNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPortNoActionPerformed(evt);
            }
        });

        bStart.setText("Start");
        bStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStartActionPerformed(evt);
            }
        });

        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        bConnect.setText("Connect");
        bConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConnectActionPerformed(evt);
            }
        });

        jLabel3.setText("Guess");

        tWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tWordActionPerformed(evt);
            }
        });

        bSend.setText("Send");
        bSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tHostName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tPortNo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bConnect)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(159, 159, 159)
                                                .addComponent(lLife))
                                            .addComponent(lWrong)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lTry, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(tWord, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(bSend))))
                                        .addGap(64, 64, 64)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bStart, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bExit, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lScore, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lWord, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lHint, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(lScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tHostName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(tPortNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bConnect))
                        .addGap(18, 18, 18)
                        .addComponent(tDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bStart, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lHint, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lWord, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tWord, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSend)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lScore, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bExit)
                    .addComponent(lWrong)
                    .addComponent(lTry, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(lLife, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tHostNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHostNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tHostNameActionPerformed

    private void tPortNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPortNoActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_tPortNoActionPerformed

    private void bStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStartActionPerformed
        // TODO add your handling code here:
        Thread t = new Thread( new Runnable() {
            public void run()
            {
               try
                {
                    pout.println("start");
                    String getmsg=bin.readLine();
                    lWord.setText("Word Hints : ");
                    lHint.setText(getmsg);
                    bStart.setEnabled(false);
                    bSend.setEnabled(true);
                    getmsg = bin.readLine();
                    lLife.setText("Life  " + getmsg);
                    lScore1.setText("Score");
                    lWrong.setText("Wrong Attempt: ");
                    lTry.setText("");

                }
                catch (IOException e)
                {
                    System.err.println(e);
                }
            }
        });
        t.start();
    }//GEN-LAST:event_bStartActionPerformed

    private void bConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConnectActionPerformed
        // TODO add your handling code here:
         Thread t = new Thread( new Runnable() {

        public void run() {

        String hostname= tHostName.getText();
          //String hostname = "localhost";
        int port = Integer.parseInt(tPortNo.getText());

          //int port = 5000;

        try {
        socket = new Socket(hostname, port);
        System.out.println("Connected: ");
        tDisplay.setText("Server Connected Successfully");

        bConnect.setEnabled(false);
        bStart.setEnabled(true);

        in= socket.getInputStream();
        out= socket.getOutputStream();
        pout=new PrintWriter(out,true);
        bin = new BufferedReader(new InputStreamReader(in));

        }

        catch (Exception e){
        System.out.println("FAILED: "+ e);
        tDisplay.setText("Server not Found");
        }
      }
        
     });

         t.start();

    }//GEN-LAST:event_bConnectActionPerformed

    private void bSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSendActionPerformed
        // TODO add your handling code here:
        Thread t = new Thread( new Runnable() {
            public void run()
            {
                try
                {
                    String letter,msg,hints;
                    letter = tWord.getText().trim();
                    tWord.setText("");
                    pout.println(letter);
                    boolean flag = false;



                    msg = bin.readLine();
                    if(msg.equals("Correct"))
                    {
                        msg = bin.readLine();
                        lHint.setText(msg);

                        msg = bin.readLine();
                        
                        lLife.setText("Congratulation");
                        lScore.setText(msg);

                        bSend.setEnabled(false);
                        bStart.setEnabled(true);
                    }

                    if(msg.equals("Incorrect"))
                    {
                        msg=bin.readLine();
                        if(msg.equals("0"))  
                        {
                            lLife.setText("Game Over. You Loose");

                            msg = bin.readLine();
                            lScore.setText(msg);

                            msg = bin.readLine();
                            lHint.setText(msg);
                                                                                 
                            bSend.setEnabled(false);
                            bStart.setEnabled(true);
                        }
                        else
                        {
                            lLife.setText("Chance Left: " + msg);
                        }
                    }

                    if(msg.equals("YES"))
                    {
                        hints = bin.readLine();
                        lHint.setText(hints);
                    }

                    if(msg.equals("NO"))
                    {
                        msg=bin.readLine();
                        if(msg.equals("0"))
                        {
                            lLife.setText("Game Over. You Loose");

                            msg = bin.readLine();
                            lScore.setText(msg);
                                                  
                            msg = bin.readLine();
                            msg = bin.readLine();
                            System.out.println(msg);
                            lHint.setText(msg);
                                                                                   
                            bSend.setEnabled(false);
                            bStart.setEnabled(true);
                            
                        }
                        else
                        {
                            lTry.setText( lTry.getText()+" "+letter);
                            lLife.setText("Chance Left: " + msg);
                        }
                        
                    }

                    if(msg.equals("Done"))
                    {
                        lLife.setText("Congratulation");
                       
                        hints = bin.readLine();
                        lHint.setText(hints);

                        msg = bin.readLine();
                        lScore.setText(msg);

                        bSend.setEnabled(false);
                        bStart.setEnabled(true);

                    }
                }
                catch (IOException e)
                {
                    System.err.println(e);
                }
            }
        });
        t.start();

    }//GEN-LAST:event_bSendActionPerformed

    private void tWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tWordActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        Thread t = new Thread( new Runnable() {
            public void run()
            {
               try{
                    pout.println("end");
                    in.close();
                    out.close();
                    socket.close();
                  }
               catch(IOException e)
               {
                    System.err.println(e);
                }
                System.exit(0);
            }
        });
        t.start();
    }//GEN-LAST:event_bExitActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConnect;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bSend;
    private javax.swing.JButton bStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lHint;
    private javax.swing.JLabel lLife;
    private javax.swing.JLabel lScore;
    private javax.swing.JLabel lScore1;
    private javax.swing.JLabel lTry;
    private javax.swing.JLabel lWord;
    private javax.swing.JLabel lWrong;
    private javax.swing.JLabel tDisplay;
    private javax.swing.JTextField tHostName;
    private javax.swing.JTextField tPortNo;
    private javax.swing.JTextField tWord;
    // End of variables declaration//GEN-END:variables

}
